/*
 * RoCNet
 * sqlite3 table definitions for the scheduler
 * Author: Anselm Meyn
*/

CREATE TABLE hosts (
	id INTEGER PRIMARY KEY,
	name VARCHAR(32) UNIQUE NOT NULL,
	rptInterval INTEGER DEFAULT 14400
);

CREATE TABLE hostIfs (
	id INTEGER PRIMARY KEY,
	hostId INTEGER NOT NULL,
	ipv4 VARCHAR(16),
	dns VARCHAR(255) DEFAULT NULL,
	port INTEGER DEFAULT 10057,
	FOREIGN KEY (hostId) REFERENCES hosts(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE hostRunInfo (
	hostId INTEGER UNIQUE NOT NULL,
	lastStart INTEGER DEFAULT 0,
	FOREIGN KEY(hostId) REFERENCES hosts(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE testItems (
	id INTEGER PRIMARY KEY,
	key VARCHAR(255) UNIQUE NOT NULL,
	duration INTEGER DEFAULT 30,
	srvSetup VARCHAR(255) DEFAULT NULL
);

CREATE TABLE testHostMap (
	testId INTEGER NOT NULL,
	hostId INTEGER NOT NULL,
	PRIMARY KEY (testId, hostId) ON CONFLICT IGNORE,
	FOREIGN KEY(testId) REFERENCES testItems(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(hostId) REFERENCES hosts(id) ON UPDATE CASCADE ON DELETE CASCADE
);
