#ifndef __VERSION_H__
#define __VERSION_H__

#define ROCNET_STR2(str)	#str
#define ROCNET_STR(str)	ROCNET_STR2(str)

#define APPLICATION_NAME	"Rocnet Agent"
#define ROCNET_REVDATE		"19 December 2013"
#define ROCNET_VERSION_MAJOR	0
#define ROCNET_VERSION_MINOR	1
#define ROCNET_VERSION_PATCH	0
#define ROCNET_VERSION_REVISION	0
#define ROCNET_VERSION_RC	""
#define ROCNET_VERSION		ROCNET_STR(ROCNET_VERSION_MAJOR) "." ROCNET_STR(ROCNET_VERSION_MINOR) "." \
							ROCNET_STR(ROCNET_VERSION_PATCH) ROCNET_VERSION_RC
#define ROCNET_REVISION		ROCNET_STR(ROCNET_VERSION_REVISION)

#endif /* __VERSION_H__ */
